donghu/urls.py
from django.urls import path
from . import views

app_name = 'donghu'
urlpatterns = [
    path('', views.user_login),
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('sendcode/', views.sendcode, name='sendcode'),
    path('sendcode/code', views.identifycode, name="identifycode"),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('category/<slug:category_name_slug>/', views.category, name='category'),
    path('category/<slug:category_name_slug>/page=<int:page>/', 
        views.category, name='category'),
    path('add_article', views.add_article, name='addarticle'),
    path('category/<slug:category_name_slug>/<slug:username>/<int:aid>',
        views.detail, name='detail'),
    path('category/delete/<int:aid>/<slug:category_name_slug>/', 
        views.delete_article, name="delete"),
    path('comment/', views.submit_comment, name='comment'),
    path('delete/<slug:category_name_slug>/<int:aid>/<int:cid>/', views.delete_comment, name='delete_com'),
    path('personal/<slug:username>/<int:uid>', views.personal, name='personal'),
    path('personal/profile', views.profile, name='profile'),
    path('search/', views.search, name='search'),

    path('polls/<int:question_id>', views.vote_detail, name='vote_detail'),
    path('polls/<int:question_id>/vote', views.vote, name='vote'),
    path('polls/<int:question_id>/results', views.results, name='results'),
    path('polls/addvote', views.add_vote, name='add_vote'),
    path('advancedsearch', views.advanced_search, name='advanced_search'),
]

donghubbs/urls.py
from django.contrib import admin
from django.contrib import auth
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('donghu.urls')),
    # path('donghu', include('donghu.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

donghu/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # email = models.EmailField(max_length=40)
    head = models.ImageField(upload_to='profile_images', blank=True, null=True)
    gender = models.CharField(max_length=3, blank=True, null=True)
    motto = models.CharField(max_length=40, blank=True, null=True)
    sustime = models.DateTimeField(null=True) # 封号开始时间
    exper = models.IntegerField(default=0)
    grade = models.IntegerField(default=1)

    def __str__(self):
        return self.user.username

class Module(models.Model):
    name = models.CharField(max_length=20, unique=True)
    name_zh = models.CharField(max_length=30, unique=True)
    views = models.PositiveIntegerField(default=0)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Module, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
 
class Article(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE, to_field='slug')
    title = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    lable = models.CharField(max_length=10, blank=True)
    content = models.TextField()
    content_ismd = models.BooleanField(default=False)
    create_time = models.DateTimeField(auto_now_add=True)
    is_sticky = models.BooleanField(default=False)
    is_highlight = models.BooleanField(default=False)
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class Commentary(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)

class ReCommentary(models.Model):
    from_id = models.ForeignKey(User, on_delete=models.CASCADE)
    to_id = models.ForeignKey(Commentary, on_delete=models.CASCADE)
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

class Message(models.Model):
    '''
    谁(from)评论/点赞了谁(to)
    action是行为，1为like 2为评论 3为分享
    args:
        action: 1: likes; 2: comments; 3: share;
    '''
    # 两个外键都来自User表，所以需要加related_name，related_name不能为python保留字
    id_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name='id_from')
    id_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='id_to')
    action = models.IntegerField()


# 以下为投票字段

class Question(models.Model):
    title = models.CharField(max_length=200)
    create_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_times = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Voter(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    voter_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '{} | {}'.format(self.voter_id.username, self.choice.choice_text)

donghu/forms.py
from django import forms
from django.contrib.auth.models import User
from donghu.models import UserProfile
from django.template import loader
from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import EmailMultiAlternatives

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('head', 'gender', 'motto')

class CustomPasswordResetForm(PasswordResetForm):
    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)
        print(subject, '---------------', body)

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()

donghu/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.urls import reverse_lazy
from django.db.models import Q, F

from donghu.utils import sendyzm
from donghu.forms import UserForm
from donghu.models import UserProfile
from donghu.models import Article, Module, Commentary, ReCommentary
from donghu.models import Question, Choice, Voter

import json
from donghu import utils

# Create your views here.
def index(request):
    module_list = Module.objects.all()
    modules = {}
    for i in module_list:
        if i.name == 'vote':
            modules[i] = (Question.objects.all().order_by('-create_time')[:8])
        else:
            modules[i] = (Article.objects.filter(module=i).order_by('-create_time')[:8])


    hot_article_list = Article.objects.all().order_by('-likes')[:8]

    context_dict = {'category': 'index', 'modules':modules, 'hot_article_list':hot_article_list}

    return render(request, 'donghu/index.html', context_dict)

def register(request):
    registered = False
    if request.method == 'POST':
        error_code = {'name':1, 'email': 2, 'yzm': 4}
        context_dict = {'success': False, 'state': 0}

        # 判断验证码是否正确
        if request.session['securityCode'] != request.POST.get("yzm"):
        # if '123' != request.POST.get('yzm'): # 测试时使用
            context_dict['state'] += error_code['yzm']
            return HttpResponse(json.dumps(context_dict))

        # 尝试从数据库中获取邮箱
        try:
            User.objects.get(email=request.POST.get('email'))
        except:
            # 有异常证明该地址不存在
            print(request.POST.get('email'))
        else:
            # 该邮箱已被注册
            context_dict['state'] += error_code['email']
            return HttpResponse(json.dumps(context_dict))

        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            print('---valid')
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            # 注册成功，自动登录跳转到首页
            user = authenticate(username=user.username, password=request.POST.get("password"))
            login(request, user)
            return HttpResponse(json.dumps({'success': True}))
        else:
            context_dict['state'] += error_code['name']

            return HttpResponse(json.dumps(context_dict))

    context_dict = {'registered': registered}
    return render(request, 'donghu/register.html', context_dict)

def sendcode(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        state, yzm = sendyzm(email)
        print('----------state:'+str(state))
        # 发送成功
        if state:
            request.session['securityCode'] = yzm
            return HttpResponse(json.dumps({"res":True}))
        else:
            return HttpResponse()

def identifycode(request):

    if request.method == "POST":
        # get到的是字符串类型
        species = request.POST.get('species')
        if species == '1':
            if request.session['securityCode'] == request.POST.get("yzm"):
            # if '123' == request.POST.get("yzm"):

                # request.session['pass'] = True 不可以
                return HttpResponse(json.dumps({"state":True}))
            else:
                return HttpResponse(json.dumps({"state":False}))


        if species == '2':
            try:
                # get会抛出异常，filter不会
                User.objects.get(username=request.POST.get('username'))
            except:
                return HttpResponse(json.dumps({"namestate":True}))
            else:
                return HttpResponse(json.dumps({'namestate':False}))

    return HttpResponse(json.dumps({"state":False}))


# 需要修改
def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/index/')
            else:
                if utils.can_login(user)[0]:
                    login(request, user)
                    return HttpResponseRedirect('/index/')
                else:
                    return render(request, 'donghu/login.html', {'errors': '因违规操作，您的账号暂时无法登录请在'+utils.can_login(user)[1]+'后登录'})
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return render(request, 'donghu/login.html', {'errors': '账号或密码错误！'})
    else:
        if request.user.username!='':
            return HttpResponseRedirect('/index/')
        return render(request, 'donghu/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def category(request, category_name_slug, page=1):
    context_dict = {'curpage':page, 'category': category_name_slug}
    context_dict['modules'] = Module.objects.all()

    page = page*10

    if category_name_slug == 'vote':
        article_list = Question.objects.all().order_by('-create_time')
    else:
        article_list = Article.objects.filter(module=category_name_slug).order_by('-create_time')
        context_dict['top_list'] = article_list.filter(is_sticky=True).order_by('-create_time')[:5]
        article_list = article_list.filter(is_sticky=False)
        
    items = len(article_list)
    context_dict['pagenums'] = items//10 if items%10==0 else items//10+1
    
    article_list = article_list[page-10:page]
    context_dict['article_list'] = article_list

    return render(request, 'donghu/category.html', context_dict)

@login_required
def add_article(request):
    # 如果账号已经被禁
    if not request.user.is_active:
        logout(request)
        return render(request, 'donghu/login.html', {'errors': '因违规操作，您的账号暂时无法登录'})

    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        try:
            user = User.objects.get(username=request.user)
        except Exception:
            # print(Exception)
            return HttpResponse('用户信息错误，请重新登录')
        try:
            module = Module.objects.get(name=request.POST.get('module'))
        except:
            return HttpResponse("分类丢了，请重新填写。")
        c = Article(module=module, title=title,author=user, content=content, content_ismd=True)
        c.save()
        return category(request, module.name)
    return render(request, 'donghu/index.html')

def detail(request, category_name_slug, username, aid):

    try:
        a = Article.objects.get(id = aid)
    except:
        return render(request, 'donghu/404.html')
    if not request.session.get('read{}'.format(aid)):
        request.session['read{}'.format(aid)] = True
        a.views += 1
        a.save()

    comment_list = Commentary.objects.filter(article=a)
    recomment_list = {}
    for comment in comment_list:
        recomment_list[comment] = ReCommentary.objects.filter(to_id=comment)
    context_dict = {"passage": a, 'comments': recomment_list, 'category': category_name_slug}
    return render(request, 'donghu/passage.html', context_dict)

@login_required
def delete_article(request, aid, category_name_slug):
    
    if category_name_slug == 'vote':
        try:
            a = Question.objects.get(pk = aid)
        except:
            return HttpResponseRedirect('/404.html')
        else:
            a.delete()
        return HttpResponseRedirect('/category/vote')

    try:
        a = Article.objects.get(id=aid)
    except:
        return HttpResponseRedirect('/404.html')
    
    user = a.author

    if (request.user == a.author or 
    request.user.has_perm('donghu.have_permission_'+category_name_slug)):
        a.delete()

    # 封号
    if (request.method == 'POST' and 
    request.user.has_perm('donghu.have_permission_'+category_name_slug)):
        utils.suspend(user) # 暂封账号
        return JsonResponse({'success':True})

    return HttpResponseRedirect('/category/'+category_name_slug)

@login_required
def delete_comment(request, category_name_slug, aid, cid):
    try:
        c = Commentary.objects.get(id=cid)
    except:
        return HttpResponseRedirect('/404.html')


    user = c.author

    # TODO(huilight@oulook.com): 管理员，版主等亦可删除
    if (request.user == c.author or
    request.user.has_perm('donghu.have_permission_'+category_name_slug)):
        c.delete()

    # 封号
    if (request.method == 'POST' and 
    request.user.has_perm('donghu.have_permission_'+category_name_slug)):
        utils.suspend(user) # 暂封账号
        return JsonResponse({'success':True})

    try:
        a = Article.objects.get(id = aid)
    except:
        return HttpResponseRedirect('/404.html')

    return detail(request, category_name_slug, a.author, aid)

@login_required
def submit_comment(request):
    try:
        article = Article.objects.get(id=request.POST.get('to'))
    except:
        return JsonResponse({'success':False})

    content = request.POST.get('content')
    # content = utils.replace(content)
    com = Commentary(article=article, author=request.user, content=content)
    com.save()
    return JsonResponse({'success':True})

@login_required
def personal(request, username, uid):
    '''
    两个入口：
        一、 自己查看自己的个人中心
            显示个人资料入口
            显示与我相关  建立相应表，有用户评论或 @我 时，在表中加入数据，另一表格有应已读标志位
                用来确定是否有未读消息
            列出我发表的文章等
        二、 他人查看
            列出发表的文章
    '''
    context_dict = {'is_visitor': True}
    context_dict['article_list'] = Article.objects.filter(author=uid).order_by('-create_time')
    if request.user.id == uid:

donghu/templates/donghu/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load donghu_template_tags %}
<html>
<head>
    <title>
    {% block title_block %}
        DonghuBBS
    {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    {% block head_block %}
    {% endblock %}
    
</head>
<body>
    <div class="mobilenav">东湖论坛<img id="menu" src="{% static 'img/menu.png' %}"></div>
    {% get_nav_list category user %}
    <div>
<!--         <ul>
            {% if not user.is_authenticated %}
                <li><a href="{% url 'donghu:login' %}">登录</a></li>
                <li><a href="{% url 'donghu:register' %}">注册</a></li>
            {% else %}
                <li><a href="{% url 'donghu:logout' %}">注销</a></li>
            {% endif %}
        </ul> -->
    </div>
<div style="height: 98%;">
    {% block body_block %}
    {% endblock %}
</div>
    {% block js_block %}
    {% endblock %}

<!-- <footer>
    <p>©2019 Donghu </p>
</footer> -->
    <script type="text/javascript">
        var stat = 1;
        $("#menu").click(function(){
            if (stat==1){
                $(".nav").show();
                stat = 0;
            }else{
                $(".nav").hide();
                stat = 1;
            }
        })
    </script>
</body>
</html>

donghu/templates/donghu/category.html
{% extends 'donghu/base.html' %}

{% load staticfiles %}
{% load donghu_template_filters %}

{% block title_block %}
    {{category_name}}
{% endblock %}

{% block head_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/category.css' %}">

{% endblock %}

{% block body_block %}
    <div class="body-block">
    <form class="search-form" id="user_form" method="post"
        action="{% url 'donghu:search' %}">
        {% csrf_token %}
        {% if category == 'vote' %}
        <a href="{% url 'donghu:add_vote' %}" class="btn vote">
            添加投票
        </a>
        {% endif %}

        <input class="search-text" type="text" size="50" required="" name="search" placeholder="Search" id="query" />
        <input class="btn btn-primary" type="submit" name="submit" value="搜索">
        <a class="btn" href="{% url 'donghu:advanced_search' %}" style="margin-left: -8px">高级搜索</a>
    </form>
    <div>
        {% if article_list %}

        <!-- Display search results in an ordered list -->
        <div class="listGroup">
            {% for item in top_list %}
                 <div class="listGroupItem">
                    <div>
                    {% if category == 'vote' %}
                        <span class="views">{{ item.vote_times|transform }}</span>
                        <a href="{% url 'donghu:vote_detail' item.id %}">{{ item.title }}</a>
                    {% else %}
                                <span style="color:red">[置顶]</span>
                                <a href="{% url 'donghu:detail' category item.author item.id %}">{{ item.title }}</a>
                            <span class="info">
                              {% if item.author == user and category == 'vote' %}
                                 <a class='delete' href="{% url 'donghu:delete' item.id category %}">删除</a>
                                {% endif %}
                             <a class="username" href="{% url 'donghu:personal' item.author.username item.author.id %}">{{item.author.username}}</a>
                              {{item.create_time|date:'m-d'}}
                        </span>
                    {% endif %}
                    </div>
                </div>
            {% endfor %}
            
            {% for item in article_list %}
                <div class="listGroupItem">
                    <div>

                    {% if category == 'vote' %}
                        <span class="views">{{ item.vote_times|transform }}</span>
                        <a href="{% url 'donghu:vote_detail' item.id %}">{{ item.title }}</a>
                    {% else %}
                        {% if not item.is_sticky %}
                        <span class="views">{{ item.views|transform }}</span>
                        {% if item.is_highlight %}
                                <span style="color:red; font-weight: 700;">精</span>
                                <a style="color: #996600" href="{% url 'donghu:detail' category item.author item.id %}">{{ item.title }}</a>
                        {% else %}
                                <a href="{% url 'donghu:detail' category item.author item.id %}">{{ item.title }}</a>
                        {% endif %}
                        {% endif %}
                    {% endif %}

                    <span class="info">
                    {% if item.author == user and category == 'vote' %}
                        <a class='delete' href="{% url 'donghu:delete' item.id category %}">删除</a>
                    {% endif %}
                    <a class="username" href="{% url 'donghu:personal' item.author.username item.author.id %}">{{item.author.username}}</a>
                    {{item.create_time|date:'m-d'}}
                    </span>
                    </div>
<!--                     <p class="listGroupItemText">{{ item.content }}</p> -->
                        
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    
    <div id="pageindex">
    </div>
    {% if category != 'vote' %}
    <!-- 编辑器 -->
    <div class="editor">
        <form  autocomplete="off" method="post" action="{% url 'donghu:addarticle'  %}">
            {% csrf_token %}
            <input type="text" name="module" value="{{category}}" style="display: none;">
            <div>
                <span>标题</span>
                <input id="title" type="text" name="title" maxlength="48" required="" >
                <input id="submit" type="submit" class="submit"   value="发表">
            </div>
            <div>
                <textarea id="content" required="" name="content"></textarea>
            </div>
        </form>
    </div>
    
    <script type="text/javascript">
        if ({{pagenums}}>1){
            var link = ""
            if({{curpage}}!=1){
                link += "<a href='/category/{{category}}/page="+
                ({{curpage}}-1)+"'>prev</a>"
            }
            for(var i=1; i<={{pagenums}}; i++){
                link += "<a href='/category/{{category}}/page="+ i+"'>"+i+"</a>"
            }
            if({{curpage}}!={{pagenums}}){
                link += "<a href='/category/{{category}}/page="+
                ({{curpage}}+1)+"'>next</a>"
            }
            $("#pageindex").html(link)
        }
    </script>
    {% endif %}
</div>
{% endblock %}

donghu/templates/donghu/nav.html
<div class="nav">
    <ul>
        <li>
        {% if act_mod == 'index' %}
            <a class="selection" href="{% url 'donghu:index' %}">首页</a>
        {% else %}
            <a href="{% url 'donghu:index' %}">首页</a>
        {% endif %}
        </li>
        {% if mods %}
            {% for i in mods %}    
                <li>
                {% if i.name == act_mod %}
                    <a class="selection" href="{% url 'donghu:category' i.name %}"> {{i.name_zh}}</a>
                {% else %}
                    <a href="{% url 'donghu:category' i.name %}">{{i.name_zh}}</a>
                {% endif %}
                </li>
            {% endfor %}
        {% endif %}
        <span>
            {% if not user.is_authenticated %}
                <li><a href="{% url 'donghu:login' %}">登录</a></li>
                <li><a href="{% url 'donghu:register' %}">注册</a></li>
            {% else %}
                <li class="alast"><a class="alastuser" href="">{{user.username}}</a>
                    <ul  class="dnav">
                        <li><a href="{% url 'donghu:personal' user.username user.id %}">个人中心</a></li>
                        <li><a href="{% url 'donghu:logout' %}">注销</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'donghu:logout' %}">注销</a></li>
            {% endif %}
        </span>

    </ul>
</div>

donghu/templates/donghu/personalpage.html
{% extends 'donghu/base.html' %}
{% load staticfiles %}

{% block head_block %}
<style type="text/css">
.navlist{
    width:160px;
    height:100%; 
    padding: 10px 0; 
    float: left; 
    background: #f0f0f0;
     background: linear-gradient(#f0f0f0, white);
    font-size: 18px;
}
ul{
    list-style:none;
}
.navlist a{
    width: 100%;
    display: inline-block;
    margin: 4px 0;
    padding-left: 10px;
}
.navlist a:hover{
    color: white;
    background: #666;
}
.title{
    font-size: 16px;
    font-weight: 800;
    color: black;

}
.alist{
    margin-top: 10px;
}
.alist li{
    padding: 4px 0;
    position: relative;
}
.alist li span{
    text-align: right;
    position: absolute;
    right: 10px;
}

{% if not is_visitor %}
.list{
    width: 700px;
/*    margin: 8px;
    padding:10px;*/
    padding: 0 10px;
    float: left;
}

.show{
    float: right;
    width: 16px;
    height: 16px;
    display: inline-block;
    background: url(/static/img/down.png);
    transform: scaleY(-1);
    cursor: pointer;
}
{% endif %}
</style>
<script type="text/javascript">
    // TODO: 显示隐藏按钮切换
    var at1 = [1,1,1];
    function b(fid, i){
        $("#"+fid).slideToggle();
        if(at1[i] == 1){
            at1[i] = 0;
            document.getElementById("show-or-hide"+i).style.transform="scaleY(1)";
        }
        else{
            at1[i] = 1;
            document.getElementById("show-or-hide"+i).style.transform="scaleY(-1)";
        }
    }
</script>
{% endblock%}


{% block body_block %}
    
    <div style="width: 950px; height: 100%; margin: 8px auto; text-align: left;">
        {% if not is_visitor %}
        <div class="navlist">
            <ul>
                <li><a id="info">个人资料</a></li>
                <li><a href="">我的消息</a></li>
                <li><a onclick="reopen('art')">发表的文章</a></li>
                <li><a onclick="reopen('com')">发表的评论</a></li>
                <li><a onclick="reopen('pol')">发起的投票</a></li>
                <li><a >我关注的</a></li>
                <li><a >关注我的</a></li>
                <li><a href="/auth/password_change">修改密码</a></li>
            </ul>    
        </div>
        {% endif %}

        <div class="list" id="list">
            <div class="alist">
                <div class="title" id="art">发表的文章
                <div class="show" id="show-or-hide0" onclick="b('art1',0)"></div>
                </div>
                <hr>

                <ul  id="art1">
                {% for i in article_list %}
                    <li>
                        <a href="{% url 'donghu:detail' i.module.name i.author i.id %}">{{ i.title }}</a>
                        <span>{{ i.module.name_zh }} {{i.create_time|date:'m-d'}}</span>
                    </li>
                {% endfor %}
                </ul>
            </div>

            {% if not is_visitor %}
            
            <div class="alist">
                    <div class="title" id="com">做出的评论
                    <div class="show" id="show-or-hide1" onclick="b('art2', 1)"></div>
                </div>
                <hr>

                <ul id="art2">
                {% if comment_list %}
                {% for i in comment_list %}
                    <li><a href="{% url 'donghu:detail' i.article.module.name i.article.author i.article.id %}#{{i.id}}">

                        {{i.content|slice:":20"}}

                    </a>
                        <span>{{ i.article.module.name_zh }} {{i.create_time|date:'m-d'}}</span>
                    </li>
                {% endfor %}
                {% endif %}
                </ul>
            </div>
            

            <div class="alist">
                <div class="title" id="pol">发起的投票
                    <div  class="show" id="show-or-hide2" onclick="b('art3',2)"></div>
                </div>
                <hr>

                <ul id="art3">
                {% for i in poll_list %}
                    <li><a href="{% url 'donghu:vote_detail' i.id %}">{{ i.title }}</a>
                    <span>投票 {{i.create_time|date:'m-d'}}</span>
                    </li>
                {% endfor %}
                </ul>
            </div>
            

            {% endif %}
        </div>
    </div>
    <div class="clear"></div>

<script type="text/javascript">
    var content = $("#list").html()
    $("#info").click(function(){

        $("#list").load("{% url 'donghu:profile' %}");
    })
    function reopen(tag){
        $("#list").html(content)       
        window.location.href="{% url 'donghu:personal' user.username user.id %}#"+tag;
    }
</script>
{% endblock %}

donghu/templates/donghu/vote_detail.html
{% extends 'donghu/base.html' %}
{% load staticfiles %}

{% block head_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/vote_detail.css' %}">
{% endblock %}

{% block body_block %}
<div class="wrap">
    <h1>{{ question.title }}</h1>

{% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}

<form  action="{% url 'donghu:vote' question.id %}" method="post">
{% csrf_token %}
<div class="list">
{% for choice in question.choice_set.all %}
    <div class="item">
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    </div>
{% endfor %}
<div>
<input class="btn" type="submit" value="投票">
<a class="btn" href="{% url 'donghu:results' question.id %}" >查看结果</a>
</div>
</div>
</form>
</div>
{% endblock %}